-- Completa el esquema de la base LOCAL (copia de marzo de 2026) con lo que
-- producción añadió después y el código actual necesita.
--
-- Solo aditivo: CREATE TABLE / ADD COLUMN con IF NOT EXISTS. No borra ni
-- modifica nada existente y se puede volver a ejecutar sin efecto.
--
--   psql -h localhost -U micrositio -d micrositio -v ON_ERROR_STOP=1 -1 -f local/completar-esquema.sql
--
-- Procedencia de los tipos: producción no expone su DDL con la clave anon, así
-- que se dedujeron de valores reales leídos por la API REST, de los esquemas
-- Zod y del uso en los repositorios. Donde producción solo tiene NULL
-- (empleado.image) se asume text, que es lo que guarda usuarios.image (una URL).
-- Las restricciones son las mínimas que el código necesita: mejor aceptar algo
-- que producción aceptaría que rechazarlo.
--
-- Las tablas nuevas quedan VACÍAS: esto trae la estructura, no los datos.

-- ---------------------------------------------------------------------------
-- Tablas nuevas
-- ---------------------------------------------------------------------------

-- habilidadesRepositorio: filtra por id_empleado, actualiza y borra por
-- id_habilidad. habilidadService exige nombre_habilidad.
CREATE TABLE IF NOT EXISTS public.habilidades (
    id_habilidad      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado       integer NOT NULL REFERENCES public.empleado (id_empleado),
    nombre_habilidad  text    NOT NULL,
    nivel             text
);
CREATE INDEX IF NOT EXISTS habilidades_id_empleado_idx ON public.habilidades (id_empleado);

-- servicioRepository: lee y ordena por id. Campos del servicioSchema (Zod).
CREATE TABLE IF NOT EXISTS public.servicio (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         text    NOT NULL,
    descripcion    text,
    objetivo       text,
    entregables    text,
    precio_aprox   numeric,
    horas_totales  numeric,
    categoria      text,
    created_at     timestamp with time zone DEFAULT now(),
    updated_at     timestamp with time zone DEFAULT now()
);

-- sesionRepository.crear inserta SOLO {id_empleado, thread_id}: todo lo demás
-- necesita valor por defecto. thread_id se busca con maybeSingle(), así que
-- tiene que ser único. id_empleado admite NULL porque un VISITANTE puede no
-- tener empleado asociado.
CREATE TABLE IF NOT EXISTS public.sesion (
    id_sesion    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado  integer REFERENCES public.empleado (id_empleado),
    thread_id    text    NOT NULL UNIQUE,
    titulo       text,
    activo       boolean NOT NULL DEFAULT true,
    created_at   timestamp with time zone NOT NULL DEFAULT now(),
    updated_at   timestamp with time zone NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS sesion_id_empleado_idx ON public.sesion (id_empleado);

-- ---------------------------------------------------------------------------
-- Columnas nuevas en tablas existentes
-- ---------------------------------------------------------------------------

-- agenteRepository filtra la búsqueda por categoria: sin ella, /search da 500.
ALTER TABLE public.agente
    ADD COLUMN IF NOT EXISTS categoria text;

-- Perfil y Equipo. fecha_ingreso llega de producción como YYYY-MM-DD.
ALTER TABLE public.empleado
    ADD COLUMN IF NOT EXISTS cargo          text,
    ADD COLUMN IF NOT EXISTS departamento   text,
    ADD COLUMN IF NOT EXISTS infopersonal   text,
    ADD COLUMN IF NOT EXISTS fecha_ingreso  date,
    ADD COLUMN IF NOT EXISTS image          text;

-- usuarioRepository guarda aquí la URL pública de la foto de perfil.
ALTER TABLE public.usuarios
    ADD COLUMN IF NOT EXISTS image text;

-- No se añaden agente.modelo, temperatura ni tools: existen en producción pero
-- el código no los usa.

-- PostgREST cachea el esquema: sin esto seguiría respondiendo que las tablas
-- nuevas no existen. Se entrega al hacer COMMIT.
NOTIFY pgrst, 'reload schema';

-- ---------------------------------------------------------------------------
-- 2026-09-11 — Lo que producción tiene y la copia local no (sincronización)
-- ---------------------------------------------------------------------------
-- Solo aditivo. Los datos los copia scripts/sincronizar-desde-supabase.mjs.

-- agente: 3 columnas que el backend no usa. En producción están vacías en
-- todas las filas, así que los tipos son supuestos (el nombre manda).
ALTER TABLE agente ADD COLUMN IF NOT EXISTS modelo text;
ALTER TABLE agente ADD COLUMN IF NOT EXISTS temperatura numeric;
ALTER TABLE agente ADD COLUMN IF NOT EXISTS tools jsonb;

-- transcript: resúmenes de reuniones. La escribe y lee la Lambda de
-- transcripciones, no el backend. created_at llega sin zona horaria.
CREATE TABLE IF NOT EXISTS transcript (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proyecto text,
  resumen text,
  resumen_estructurado jsonb,
  created_at timestamp DEFAULT now()
);

-- Historial de conversaciones del agente: el esquema estándar del
-- PostgresSaver de LangGraph (lo usa la Lambda del agente, no el backend).
CREATE TABLE IF NOT EXISTS checkpoint_migrations (
  v integer PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS checkpoints (
  thread_id text NOT NULL,
  checkpoint_ns text NOT NULL DEFAULT '',
  checkpoint_id text NOT NULL,
  parent_checkpoint_id text,
  type text,
  checkpoint jsonb NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}',
  PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id)
);
CREATE TABLE IF NOT EXISTS checkpoint_blobs (
  thread_id text NOT NULL,
  checkpoint_ns text NOT NULL DEFAULT '',
  channel text NOT NULL,
  version text NOT NULL,
  type text NOT NULL,
  blob bytea,
  PRIMARY KEY (thread_id, checkpoint_ns, channel, version)
);
CREATE TABLE IF NOT EXISTS checkpoint_writes (
  thread_id text NOT NULL,
  checkpoint_ns text NOT NULL DEFAULT '',
  checkpoint_id text NOT NULL,
  task_id text NOT NULL,
  idx integer NOT NULL,
  channel text NOT NULL,
  type text,
  blob bytea NOT NULL,
  task_path text NOT NULL DEFAULT '',
  PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id, task_id, idx)
);
CREATE INDEX IF NOT EXISTS checkpoints_thread_id_idx ON checkpoints (thread_id);
CREATE INDEX IF NOT EXISTS checkpoint_blobs_thread_id_idx ON checkpoint_blobs (thread_id);
CREATE INDEX IF NOT EXISTS checkpoint_writes_thread_id_idx ON checkpoint_writes (thread_id);

-- ---------------------------------------------------------------------------
-- 2026-09-14 — Etapas de proyecto (maqueta) y rol ADMIN
-- ---------------------------------------------------------------------------
-- Solo aditivo y reejecutable.

-- Rol ADMIN: es EDITOR + aprobar proyectos. Se amplía el CHECK (no se borra
-- ninguna fila) y el usuario `admin` pasa a ese tipo.
ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_tipo_check;
ALTER TABLE usuarios ADD CONSTRAINT usuarios_tipo_check
  CHECK (tipo IN ('EDITOR', 'VISITANTE', 'ADMIN'));
UPDATE usuarios SET tipo = 'ADMIN' WHERE alias = 'admin' AND tipo <> 'ADMIN';

-- Estado de las 5 etapas de un proyecto. `datos` guarda el brief, la propuesta
-- editable y lo capturado en cada pestaña; `es_maqueta` recuerda que esto se
-- llenó con la maqueta y aún falta implementarlo de verdad.
CREATE TABLE IF NOT EXISTS proyecto_etapa (
  id_proyecto integer PRIMARY KEY REFERENCES proyecto(id_proyecto) ON DELETE CASCADE,
  etapa_actual text NOT NULL DEFAULT 'BRIEF'
    CHECK (etapa_actual IN ('BRIEF', 'PLAN', 'EJECUCION', 'IDEACION', 'RESULTADOS')),
  datos jsonb NOT NULL DEFAULT '{}'::jsonb,
  aprobado_por uuid REFERENCES usuarios(id_usuario),
  aprobado_en timestamptz,
  es_maqueta boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Cards propuestas por el plan de trabajo: existen pero no se muestran en el
-- resto de la aplicación hasta que el ADMIN aprueba el proyecto. El default
-- deja visible todo lo que ya existía.
ALTER TABLE testing_card ADD COLUMN IF NOT EXISTS es_borrador boolean NOT NULL DEFAULT false;
ALTER TABLE learning_card ADD COLUMN IF NOT EXISTS es_borrador boolean NOT NULL DEFAULT false;

-- Métricas de un accionable (pestaña Ideación), con la misma forma que las de
-- testing card: nombre + operador + criterio, y resultado que se llena después.
CREATE TABLE IF NOT EXISTS metrica_accionable (
  id_metrica_accionable integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_accionable integer NOT NULL REFERENCES accionable(id_accionable) ON DELETE CASCADE,
  nombre text NOT NULL,
  operador text,
  criterio text,
  resultado text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS metrica_accionable_id_accionable_idx ON metrica_accionable (id_accionable);

-- ---------------------------------------------------------------------------
-- 2026-09-15 — Brief del procesador de transcripts
-- ---------------------------------------------------------------------------
-- Solo aditivo y reejecutable.

-- Lo que devuelve el procesador de transcripts al pulsar Ejecutar, atado al
-- proyecto. Es distinto de la tabla `transcript` de más arriba: aquella la
-- escribe la Lambda, guarda el nombre del proyecto como texto libre (ninguna
-- de sus filas coincide con un proyecto real) y este backend no la toca.
--
-- Una fila por proyecto, como proyecto_etapa: cada Ejecutar sustituye al
-- anterior mediante upsert. De los archivos solo se guarda la referencia; el
-- binario vive en disco, en el bucket brief-docs, servido en /archivos.
-- Todo es nulable salvo la clave: el .pptx debe poder subirse sin haber
-- pulsado Ejecutar.
CREATE TABLE IF NOT EXISTS proyecto_brief (
  id_proyecto integer PRIMARY KEY REFERENCES proyecto(id_proyecto) ON DELETE CASCADE,
  nombre_proyecto text,
  transcript_id text,
  url text,
  resumen text,
  resumen_estructurado jsonb,
  origen text CHECK (origen IN ('texto', 'docx')),
  archivo_nombre text,
  archivo_url text,
  archivo_tipo text,
  archivo_tamano integer,
  pptx_nombre text,
  pptx_url text,
  pptx_tamano integer,
  ejecutado_en timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
